run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - gofmt
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - gosec
